### ISSUE TITLE
Cancellation support

### ISSUE THREAD

**Issue by maks-ivanov** [densumesh/broccoli#1]
Users should be able to cancel pending or in progress tasks
It would be extra nice to support cancellation of dependent / child tasks as well, but I don't think those concepts have been introduced yet

**Comment by cdxker** [comment]
It would be difficult as the current queueing system has no way to fetch the current position in Queue for jobs that have been scheduled. We will first need to develop a lookup system for queue'd items

**Comment by densumesh** [comment]
Fixed in https://github.com/densumesh/broccoli/commit/7858cbdc22788bb94c78a00a9c9dd8f299484d2e
